
extra: 'additional'
data_dir: 'Datasets'
extra_dir: 'additional'
ckpt_dir: 'ckpt'
n_latents: 51 #16 #23 #47
input_dims: 51 #23
n_layers: 3
n_hiddens: 64 #100 #64
n_actions: 2
batch_size: 1
test_batch: 1
n_sample: 64
log_interval: 50
save_interval: 1
max_step: 1000
n_workers: 0
run_name: RNN_MODEL

save_path: "./MODEL/RNN_MODEL"  # path to save the model files
