
n_latents: 40 #30 #58 #65 #16 
input_dims: 58 #65 #23
n_hiddens: 256
n_actions: 2
batch_size: 16
test_batch: 12
n_sample: 64
log_interval: 50
save_interval: 10
max_step: 100_0000
n_workers: 0
run_name: VAE_MODEL_CONTINUOUS
save_path: "./MODEL/VAE_MODEL_CONTINUOUS"  # path to save the model files
